#pragma once


#define DEBUG_MATRIX_SCAN_RATE

//#define QMK_WAITING_TEST_BUSY_PIN GP8
//#define QMK_WAITING_TEST_YIELD_PIN GP9


// Double Tap to Bootloader
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP25
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U




// OLED settings 0.91"
#define OLED_DISPLAY_128X32
#define I2C_DRIVER I2CD0
#define I2C0_SDA_PIN GP12
#define I2C0_SCL_PIN GP13
 
